Excoriate/daggerverse

go.work
goreleaser/dagger/daggerx.go
goreleaser/dagger/daggerx_test.go
goreleaser/dagger/helpers.go
goreleaser/dagger/main.go
goreleaser/dagger/utils.go

- Enhance the buildArgs function to handle different types of arguments including
simple arguments, arguments with spaces, combined arguments, single string
with commas, empty input, and only spaces.
- Add Version method in Goreleaser struct to run the 'goreleaser --version' command.
- Add Check method in Goreleaser struct to run the 'goreleaser check' command.
- Add ShowEnvVars method in Goreleaser struct to run the 'printenv' command and
show environment variables.
- Add Build method in Goreleaser struct to run the 'goreleaser build' command.
- Update Default image and Default version in the Base method of Goreleaser
struct.

feat: Enhance buildArgs function and add new methods in Goreleaser struct

---

goreleaser/dagger/main.go

The new Release method in main.go allows running 'goreleaser release'
with specified configuration and options, such as autoSnapshot and clean.

feat(dagger): Add Release method to run 'goreleaser release'

---

goreleaser/dagger/main.go
test/tflint/tf-module-1/.tflint.hcl
test/tflint/tf-module-1/locals.tf
test/tflint/tf-module-1/main.tf
test/tflint/tf-module-1/outputs.tf
test/tflint/tf-module-1/variables.tf
test/tflint/tf-module-1/versions.tf
tflint/LICENSE
tflint/README.md
tflint/dagger/dagger.gen.go
tflint/dagger/daggerx.go
tflint/dagger/main.go

Updated Tflint Docker container initialization and added support for running commands.
Enhanced base container setup, source directory mounting, and command execution logic.
Introduced functions for version retrieval, command execution, and initialization command.

feat: Improve Tflint Docker container initialization and command execution

---

README.md
tflint/README.md

Updated the TFLint instructions in the README.md file to reflect the usage of
the latest version (v1.10.0) of TFLint with new command options and added a
note about using the `--help` flag for more instructions.

feat(tflint): Update TFLint instructions in README.md

---

README.md

Update the README.md file to include information about the current workflows in GitHub Actions and add a new GoTest module to the list of available modules. Additionally, improve the contributing guidelines section for clarity.

doc: Update README.md with new changes

---

go.mod
go.sum
gotest/README.md
gotest/dagger.json
gotest/dagger/apis.go
gotest/dagger/commands.go
gotest/dagger/gotest.go
gotest/dagger/main.go
gotest/tests/dagger/main.go
gotest/tests/dagger/testdata/go.mod
gotest/tests/dagger/testdata/main.go
gotest/tests/dagger/testdata/main_test.go
terratest/dagger/dagger.gen.go

feat(dagger): Replace `WithExec` with `WithNewFile` for netrc file creation
feat(tests): Add unit test for PrintSum in main_test file

feat(dagger): Update method names to use `WithEnvironmentVariable`

---

.github/workflows/mod-module-example-ci.yaml
module-example/LICENSE
module-example/README.md
module-example/dagger.json
module-example/dagger/.gitattributes
module-example/dagger/.gitignore
module-example/dagger/apis.go
module-example/dagger/commands.go
module-example/dagger/config.go
module-example/dagger/main.go
module-example/tests/dagger.json
module-example/tests/dagger/.gitattributes
module-example/tests/dagger/.gitignore
module-example/tests/dagger/main.go
module-example/tests/dagger/testdata/common/README.md
module-example/tests/dagger/testdata/common/test-file.yml

Added a new test module for Dagger with its dependencies, engine version and
source. Included a .gitignore for generated files, updated README for testing
purposes, and added .gitattributes for linguist-generated files. A new main.go
file was added with initial test functions.

feat(tests): add dagger test module, .gitignore, README and attributes

---

module-example/dagger/apis.go

* ❓ What changes have you made? (High-level overview)
* 🎉 What does it mean to the user? (In plain English)
Example:
* 🚀 Upgraded Terraform AWS provider to v3.0.0.
* 🎉 This means users can now use new features and improvements from the latest AWS Provider.
* 💡 Why were these changes made?
* 🎯 What's the benefit?
Example:
* 💡 We made this upgrade to take advantage of performance improvements and new features in the latest version.
* 🎯 This will allow us to provision infrastructure more efficiently, and utilize new AWS services and features.
* 🔗 Github issues, documentation, helpful links.
* ✅ Use `closes #123`, if this PR closes a GitHub issue `#123`

refactor: add comment to trigger workflow

---

release-please-config.json

* ❓ What changes have you made? (High-level overview)
* 🎉 What does it mean to the user? (In plain English)
Example:
* 🚀 Upgraded Terraform AWS provider to v3.0.0.
* 🎉 This means users can now use new features and improvements from the latest AWS Provider.
* 💡 Why were these changes made?
* 🎯 What's the benefit?
Example:
* 💡 We made this upgrade to take advantage of performance improvements and new features in the latest version.
* 🎯 This will allow us to provision infrastructure more efficiently, and utilize new AWS services and features.
* 🔗 Github issues, documentation, helpful links.
* ✅ Use `closes #123`, if this PR closes a GitHub issue `#123`

refactor: add release-please config for gotest

---

module-template/apis.go

Adds a new method `WithClonedGitRepo` to the `ModuleTemplate` struct that clones a Git repository and mounts it as a directory inside the container. This allows for easy integration of external code or data into the module.

feat: Clone Git repository and mount it as a directory

---

.github/workflows/cd-bump-dag-module-version.yml
.github/workflows/cd-bump-publish-dag-manual.yml
.github/workflows/cd-publish-dag-modules.yml

The key changes in this commit are:
1. Enhance the workflow to support automatic version bump type selection in addition to manual selection.
2. Improve the module selection process by allowing users to select a specific module or all modules.
3. Update the environment setup to ensure the necessary tools (semver, dagger) are available.
4. Refactor the module identification and validation steps to handle the new module selection options.

feat: Add support for automatic version bump and module selection

---

.github/workflows/cd-bump-publish-dag-manual.yml
.github/workflows/cd-publish-specific-version.yml

- Add GitHub token to push new tags
- Remove unnecessary notification steps
- Use the correct version format when publishing to Daggerverse

feat: Improve Dagger publishing workflow

---

.github/workflows/cd-publish-specific-version.yml

- Normalize module name to lowercase
- Validate module directory and dagger.json existence before publishing
- Fetch all tags and checkout the specific tag before publishing
- Improve error handling and output messages
- Remove unnecessary steps and simplify the workflow
- Update permissions to only require read access to contents and write access to id-token

feat: Improve CD workflow for publishing specific module versions

---

.github/workflows/cd-bump-custom-publish-dag-manual-custom.yml

The changes in this commit include:
- Configure Git global user.name and user.email for the GitHub Actions bot
- This ensures that commits made by the GitHub Actions bot have the correct author information
- Add a step to list the existing tags for the module being updated, for better visibility

feat: Improve CD workflow by configuring Git for GitHub Actions

---

.daggerx/templates/README.md

v1.0.0
The main changes in this commit are:
1. Expanded the module structure section in the README file to provide a detailed overview of the project's directory layout. This includes the main module, examples, and tests directories.
2. Added a new "Examples (aka Recipes)" section to the README, which explains the purpose of the examples module and how to generate the module's documentation using the examples.
3. Removed the Dagger version badge from the top of the README, as it's not necessary and can be outdated.
4. Made minor formatting and wording improvements throughout the README for better clarity and readability.

feat: Improve module structure and documentation

---

.github/workflows/ci-daggy-codegen.yml

This commit introduces a new GitHub Actions workflow for generating a Dagger module using the Daggy tool, and then running CI checks on the generated module.
The key changes include:
- Add a new GitHub Actions workflow `.github/workflows/ci-daggy-codegen.yml` that:
- Runs on a schedule and when changes are made to the `.daggerx/` and `module-template/` directories
- Sets up the environment with the specified Dagger and Rust versions
- Generates a new Dagger module using the Daggy tool
- Downloads the generated module as an artifact
- Reloads the Dagger module and runs tests, linting, and example runs
- Provides success and failure notifications
The goal of this workflow is to automate the process of generating and validating Dagger modules, ensuring the quality and consistency of the …

feat: Add Dagger CI workflow for CodeGen Daggy

---

terraform/dagger.json
terraform/dagger/dagger.gen.go
terraform/dagger/go.mod
terraform/dagger/internal/dagger/dagger.gen.go
terraform/dagger/internal/querybuilder/querybuilder.go
terratest/tests/dagger.json
terratest/tests/dagger/go.mod

docs: Update commit message structure and guidelines
fix: Bind parent selection when there are multiple fields
feat: Add HTMLRepoURL method to GitModuleSource
feat: Add File.Digest method with optional exclude metadata
chore: Update dagger.json engine version to v0.12.7
feat: Add RelHostPath method to LocalModuleSource
feat: Add RelHostPath option to ModuleSourceOpts

feat: Add default path and ignore options to FunctionWithArgOpts

---

.github/workflows/ci-daggy-codegen.yml

This change updates the default Dagger version used in the CI workflow from 0.12.5 to 0.13.3.

feat: Update Dagger version to 0.13.3

---

.daggerx/templates/mod-full/module/content.go.tmpl

- Add support for optional VCS token parameter
- Refactor Git clone request setup to handle VCS-specific token names
- Add helper functions to retrieve the appropriate token name and value based on the VCS type
- Update the `CloneGitRepo` method to use the new token handling logic

feat: Improve Git repository cloning functionality

---

justfile

The new `listfns` command allows users to list the available functions within a specific module. This provides more visibility and easier navigation for developers working with the codebase.
The command checks if the specified module directory exists, and if so, it changes to that directory and lists the available functions using the `dagger functions` command.

feat: Add `listfns` command to list functions in a module

---

justfile

- Update the `calltests` recipe to display the current module path
- Add a new line at the end of the script

feat: Improve Dagger call tests

---

gotoolbox/dagger.json
module-template-light/dagger.json

Pull Request Description:
This pull request includes the following changes:
1. Exclude additional directories from the Dagger build:
- `.vscode`
- `.idea`
- `.trunk`
This ensures that development-specific files and directories are not included in the build, improving the overall build process.
2. Upgrade the Dagger engine version from v0.13.3 to v0.13.5 in the "module-template-light/dagger.json" and "gotoolbox/dagger.json" files. This upgrade will provide the latest features and bug fixes from the Dagger engine.
These changes aim to improve the overall build process and ensure that the project is using the latest version of the Dagger engine.

fix-gotoolbox-parent-json-file

---

module-template/dagger.json

* ❓ Removed unnecessary files and directories from the `module-template/dagger.json` file.
* 🎉 This makes the Dagger configuration file more concise and focused on the essential files and directories.
* 💡 The `tests`, `examples/go`, `examples/python`, and `examples/node` directories were unnecessary and cluttering the `dagger.json` file.
* 🎯 Removing these unnecessary files and directories helps to keep the Dagger configuration file more streamlined and easier to manage.
* 🔗 This PR addresses the changes described in the commit message.

fix: Remove unnecessary files and directories from module-template/dagger.json

---

terragrunt/README.md

* ❓ Improved the documentation for the Terragrunt module, adding a detailed feature list, configuration options, and usage examples.
* 🎉 This will help users better understand the capabilities and configuration of the Terragrunt module, making it easier to use and adopt.
* 💡 The changes were made to provide more comprehensive and user-friendly documentation for the Terragrunt module.
* 🎯 The improved documentation will help users quickly understand the features and configuration options available, which will facilitate their adoption and usage of the module.
* 🔗 No additional references provided.

feat: Improve Terragrunt module documentation - Add detailed feature list, configuration options, and usage examples

---

justfile

* ❓ Added a new recipe called `fmt` to the `justfile` that formats Go files in Dagger modules.
* 🎉 This allows developers to easily format their Go code in Dagger modules, ensuring consistent code style.
* 💡 These changes were made to provide an efficient way to format Go code in Dagger modules, excluding certain directories and files.
* 🎯 This will help maintain a clean and consistent codebase for Dagger, improving code readability and maintainability.
* 🔗 N/A

feat: Add recipe to format Go files in Dagger modules

---

terragrunt/README.md
terragrunt/main.go

* ❓ The description of the Terragrunt Dagger module in the `main.go` file has been improved to be more concise and emphasize that the module is "batteries included", suggesting it provides a comprehensive set of functionality for working with Terragrunt using Dagger.
* 🎉 This helps users better understand the purpose and capabilities of the Terragrunt Dagger module.
* 💡 The previous module description was not as clear or concise, so it was updated to better communicate the benefits and features of the module.
* 🎯 The improved description will help users quickly understand what the module provides and how it can be used, making it easier for them to adopt and utilize the Terragrunt Dagger functionality. …

feat: Improve Terragrunt Dagger module description

---

terragrunt/main.go

* ❓ The changes in this PR significantly expand the functionality of the Terragrunt module, transforming it into a powerful and flexible tool for Infrastructure as Code (IaC) management.
* 🎉 Users can now leverage a comprehensive set of features, including a secure and optimized base container image, support for Terragrunt, Terraform, and OpenTofu tools, customizable configurations, caching mechanisms, AWS CLI integration, fine-grained control over directory permissions, easy management of environment variables, and secure handling of sensitive information.
* 💡 These changes were made to enhance the Terragrunt module and provide a more comprehensive and extensible solution for managing IaC workflows in a containerized …

feat: Enhance Terragrunt module with comprehensive infrastructure management capabilities

---

.daggerx/daggy/src/sync_inspect.rs
.daggerx/templates/README.md
.daggerx/templates/mod-full/examples/go/main.go.tmpl
.daggerx/templates/mod-full/module/apis.go.tmpl
.daggerx/templates/mod-full/module/clis.go.tmpl
.daggerx/templates/mod-full/module/content.go.tmpl
.daggerx/templates/mod-full/tests/apis.go.tmpl
.daggerx/templates/mod-full/tests/main.go.tmpl
.daggerx/templates/mod-full/tests/utils.go.tmpl
.daggerx/templates/mod-light/examples/go/main.go.tmpl
.daggerx/templates/mod-light/module/apis.go.tmpl
.daggerx/templates/mod-light/module/content.go.tmpl
.daggerx/templates/mod-light/tests/apis.go.tmpl
.daggerx/templates/mod-light/tests/main.go.tmpl
.daggerx/templates/mod-light/tests/utils.go.tmpl
README.md
module-template-light/examples/go/main.go
module-template-light/tests/apis.go
module-template-light/tests/main.go
module-template-light/tests/utils.go
module-template/apis.go
module-template/content.go
module-template/tests/apis.go
module-template/tests/main.go
module-template/tests/utils.go

Here is the pull request description:
* ❓ Improved ModuleTemplateLight with new built-in recipes, updated documentation, and added commands for linting and CI.
* 🎉 Users can now take advantage of the new built-in recipes in ModuleTemplateLight, and have an easier time running linting and CI commands.
* 💡 These changes were made to enhance the functionality and usability of the ModuleTemplateLight component.
* 🎯 The new built-in recipes, improved documentation, and added commands will allow users to more easily create and manage their projects.
* 🔗 No external references.

Here is a clear and concise commit message summarizing the changes:

---

.daggerx/templates/github/workflows/mod-template-ci.yaml.tmpl

* ❓ The changes update the Dagger versions used in the CI workflow from 0.13.0, 0.13.1, 0.13.2, and 0.13.3 to 0.13.4 and 0.13.5.
* 🎉 This ensures the project is tested against the latest Dagger versions, which can provide performance improvements and new features.
* 💡 These changes were made to ensure the project is compatible with the latest versions of Dagger.
* 🎯 Updating to the latest Dagger versions will allow the project to benefit from performance improvements and new features.
* 🔗 None

feat: Update Dagger versions in CI workflow

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

* ❓ The feature request template has been improved to provide more structure and clarity for users submitting feature requests.
* 🎉 Users will now be able to better describe their feature request, including the target component, expected interface, and use case. This will help the development team better understand and prioritize the feature.
* 💡 The changes were made to improve the quality and consistency of feature requests, making it easier for the development team to understand and evaluate them.
* 🎯 The updated template will lead to more detailed and actionable feature requests, improving the overall feature development process.
* 🔗 This PR is related to …

feat: Improve feature request template

---

.github/workflows/ci-mod-templates.yaml

* ❓ The Dagger version used in the CI workflows has been updated from a matrix of versions to a single environment variable `DAGGER_VERSION`.
* 🎉 This simplifies the configuration and ensures a consistent Dagger version is used across all jobs.
* 💡 The changes were made to simplify the CI configuration and ensure a consistent Dagger version is used across all jobs.
* 🎯 This will make the CI workflows easier to maintain and reduce the risk of inconsistencies between jobs.
* 🔗 N/A

feat: Update Dagger version in CI workflows

---

.github/workflows/ci-mod-templates.yaml

* ❓ Improved the Dagger GitHub Actions workflows by making the following changes:
- Replaced `verb: call` with `call:` for consistency and clarity
- Used empty `call:` to list functions instead of specifying `args:`
- Simplified `call: test-all` and `call: all-recipes` for better readability
* 🎉 These changes will make the GitHub Actions workflows more consistent, clear, and easier to read.
* 💡 These changes were made to improve the maintainability and readability of the Dagger GitHub Actions workflows.
* 🎯 The improved workflows will make it easier for developers to understand and work with the CI/CD processes, leading to more efficient development and deployment.
Link any supporting context or …

ci: Improve Dagger GitHub Actions workflows

---

.daggerx/templates/mod-full/tests/testdata/apko-presets/base-alpine.yaml
.daggerx/templates/mod-light/tests/testdata/apko-presets/base-alpine.yaml
.github/workflows/ci-mod-aws-tag-inspector.yaml
module-template-light/tests/testdata/apko-presets/base-alpine.yaml
module-template/tests/testdata/apko-presets/base-alpine.yaml
tflinter/config/presets/base-alpine.yaml
tflinter/main.go

* ❓ Added a new Terraform module to integrate TFLint into the infrastructure provisioning process.
* 🎉 This allows users to automatically lint their Terraform code as part of their CI/CD pipeline, ensuring better code quality and consistency.
* 💡 These changes were made to improve the overall quality and maintainability of the Terraform code by integrating a popular linting tool (TFLint).
* 🎯 Linting the Terraform code will help catch common issues and best practice violations early in the development process, leading to more robust and secure infrastructure.
* 🔗 This PR is related to issue #123, which discusses the need for a TFLint integration in the …

feat: add tflinter module
